### ISSUE TITLE
How to use input_fn for non tf data?

### ISSUE THREAD

**Issue by amitkayal** [tensorflow/gan#11]
I found that the input_function accepts TF dataset and all the examples are being done from tfds dataset. I have hundreds of images scraped and want to have CGGAN for this. Can I have some guidance how to do using TFGAN?

**Comment by aaronsarna** [comment]
I'd recommend looking at https://www.tensorflow.org/guide/data. It gives you a number of options for turning your image files into a tf.data.Dataset, which is what the input functions expect.

**Comment by joel-shor** [comment]
You should look at the documentation for tf.Estimator's input_fn here: https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator#args_11

I'm going to close this out. Please reopen if you have any other questions.
