### ISSUE TITLE
Not getting results when converting the tf.layers implementation to tf.keras.

### ISSUE THREAD

**Issue by shubham2206** [tensorflow/gan#15]
I am getting good results when I am training unconditional GANs on MNIST dataset using tf.layers.But I am not getting any results when I am converting the same code to tf.keras.
See here, [https://stackoverflow.com/questions/59452422/unconditional-generative-adverserial-networks-on-mnist-dataset](url)

**Comment by aaronsarna** [comment]
I responded on the stackoverflow question.

We are planning to add proper Keras support, so maybe I'll leave this issue open until we get that done.
