### ISSUE TITLE
Colab Tutorial Not TF 2.x Compatible

### ISSUE THREAD

**Issue by dgrahn** [tensorflow/gan#18]
Even though the TF-Gan supports TF 2.x, the Google Colab tutorial is not TF 2.x compatible.

This should be updated to either lock the version to TF 1.x or update to support TF 2.x.

**Comment by ayushmankumar7** [comment]
Let me work on this.

**Comment by Ankuraxz** [comment]
I had worked on this to produce a GAN, You can use any dataset(Image) you want. 
[https://github.com/tensorflow/gan/pull/21](url)

**Comment by joel-shor** [comment]
Correct, the colab notebook is deisgned for TF 1.X. If you'd like to add TF 2.X support, contributions are welcome!
