### ISSUE TITLE
Update the data provider for ImageNet 2012.

### ISSUE THREAD

**Issue by Gsunshine** [tensorflow/gan#22]
Since ImageNet changed its rule of downloading the dataset, I could not directly access the dataset via tfds.load. I followed [URL](https://cloud.google.com/tpu/docs/imagenet-setup) to transform local ImageNet 2012 dataset to tfrecord files. However I find it seems to be incompatible with current tfds API, especially tfds.load as it in [data_provider.py](https://github.com/tensorflow/gan/blob/master/tensorflow_gan/examples/self_attention_estimator/data_provider.py).

I am not sure if I should rewriter the data provider to fit the tfrecord files processed by [URL](https://cloud.google.com/tpu/docs/imagenet-setup) since I am afraid the re-implementation may change the training behavior and lead to an unfair comparison or inexact reproduction.

BTW, what is the correct pipeline to reproduce SAGAN from ImageNet 2012 dataset on TPU? I think current one does not work due to the data provider. Should I download the dataset in tar files via imagennet_to_gcs.py in [URL](https://cloud.google.com/tpu/docs/imagenet-setup) and set manual_dir to tfds.load to load it to google cloud storage and continue running [data_provider.py](https://github.com/tensorflow/gan/blob/master/tensorflow_gan/examples/self_attention_estimator/data_provider.py), or re-implement the data provider to fit the results from processed tfrecords via [URL](https://cloud.google.com/tpu/docs/imagenet-setup)? 

It confused me since several official implementations from google conflict each other. The reproduction or comparison on ImageNet 2012 is quite expensive thus I start the issue rather than test it by meself.

Thx for any help!

**Comment by aaronsarna** [comment]
Sounds like the issue you're having is with tfds. It looks like you've already created an issue there https://github.com/tensorflow/datasets/issues/1739 so I assume that if that gets resolved it will just work for tfgan.

@yoeldrand @joel-shor for the SAGAN questions

**Comment by Gsunshine** [comment]
> Sounds like the issue you're having is with tfds. It looks like you've already created an issue there [tensorflow/datasets#1739](https://github.com/tensorflow/datasets/issues/1739) so I assume that if that gets resolved it will just work for tfgan.
> 
> @yoeldrand @joel-shor for the SAGAN questions

Yes. But I don't know which one is easy to be fixed, tfgan or tfds.

I think it is much harder to fix tfds.load for ImageNet 2012 due to its encapsulation. So I am working on a new data provider that is compatible with tfrecord files from [imagenet_to_gcs.py](https://github.com/tensorflow/tpu/tree/master/tools/datasets). This approach is quite new and is suggested by google cloud documents [URL](https://cloud.google.com/tpu/docs/imagenet-setup).

However the behavior of the new data provider need to be tested on TPUs. I could start a pull request to update it if it is welcomed and then you review the code and conduct a TPU run. It is also OK to fix it by official team of tfgan and I will wait for the results.

BTW, the README file of SAGAN could provide more information about the training process. Since the fig that shows SAGAN is much faster on TPUs than on GPUs reveals that TPUs seem to obtain a better FID than both results reported by original papers and on 8 * V100 GPUs, but we do not know the exact number. A comparison on TPUv3-8 is also needed since it has the same memory as 8 * V100 and it is also available for [tfrc](https://www.tensorflow.org/tfrc) program thus easy for researchers to reproduce it.

SAGAN is a very important baseline. If tfgan can provide more detailed information, it will be very beneficial to the research community. Much thx!

**Comment by aaronsarna** [comment]
I don't think tfgan is looking to move away from tfds. tfds is meant to be the canonical way to load standard datasets in TF. If it isn't working properly then they need to fix it. It may be that the way they should fix it is by following a similar protocol to imagenet_to_gcs.py.

**Comment by Gsunshine** [comment]
> I don't think tfgan is looking to move away from tfds. tfds is meant to be the canonical way to load standard datasets in TF. If it isn't working properly then they need to fix it. It may be that the way they should fix it is by following a similar protocol to imagenet_to_gcs.py.

It seems they suggest tfgan rewrite the ImageNet2012 dataset via a self-defined tfds Dataset  rather than update the protocal to google tpu team as  [imagenet_to_gcs.py](https://github.com/tensorflow/tpu/tree/master/tools/datasets). See tensorflow/datasets#1739.

**Comment by Gsunshine** [comment]
@aaronsarna I rebuild the data provider according to tpu team's [pipeline](https://github.com/tensorflow/tpu/blob/master/models/experimental/inception/inception_v3.py). It seems the code works well.

A bug is reported in SAGAN that chech_for_unused_update_ops=True raise a ValueError. I find it suppose all ema buffer in bn to be unused update ops. However there is no API in current SAGAN example to disable this check. So I set the kwarg in original tfgan implementation [](https://github.com/tensorflow/gan/blob/master/tensorflow_gan/python/train.py#L974) to False. The code runs normally then.

My tf version is 2.0.0 and tfgan is the current version.  Is this check important? Or will it impact the performance?

**Comment by aaronsarna** [comment]
I don't see anywhere in tensorflow/datasets#1739 where they suggest that tfgan change anything. tfds provides an API and tells you how to get the data that API expects. If you want to use it with data in a different format, you should expect to need to modify the code in question. You are free to make local modifications to either tfgan or tfds, but I wouldn't expect either to merge a pull request for it. Our aim is to keep the examples as simple and generic as possible. Adding many different ways to load data is really the opposite of what we're trying to do here.

Please open separate issues for the SAGAN problems you're seeing, since they're unrelated to the data provider, and we'll look into them there.

**Comment by Gsunshine** [comment]
My data loader works well now. Thx!

A new issue will be opened to report the small bug.
