### ISSUE TITLE
Computation of Sliced Wasserstein Distance numerically unstable

### ISSUE THREAD

**Issue by banelli** [tensorflow/gan#28]
The function `_normalize_patches()` defined and used [here](https://github.com/tensorflow/gan/blob/c25b27ae6e6dd174aa4956765e3e8e71be4772ab/tensorflow_gan/python/eval/sliced_wasserstein.py#L128) in  `tensorflow_gan.python.eval.sliced_wasserstein` divides by the standard deviation of the values within a patch. To respect the case where the standard deviation is zero I suggest to add a small constant for numerical stability [here](https://github.com/tensorflow/gan/blob/c25b27ae6e6dd174aa4956765e3e8e71be4772ab/tensorflow_gan/python/eval/sliced_wasserstein.py#L139):

` patches = (patches - mean) / (tf.sqrt(variance) + 1.0e-12)`

**Comment by joel-shor** [comment]
This is a good observation, but would change the value of the eval metric and make it incomparable to previously reported numbers. It might be worth proposing an alternate metric, and naming it something different!
