### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by rockerritesh** [tensorflow/gan#33]
I run  this colab in https://colab.research.google.com/github/tensorflow/gan/blob/master/tensorflow_gan/examples/colab_notebooks/tfgan_tutorial.ipynb#scrollTo=83-azWpoYsDg&uniqifier=5&line=10
and found this error
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-3b92affab886> in <module>()
      8 # Allow matplotlib images to render immediately.
      9 get_ipython().magic('matplotlib inline')
---> 10 tf.logging.set_verbosity(tf.logging.ERROR)  # Disable noisy outputs.

AttributeError: module 'tensorflow' has no attribute 'logging'

**Comment by oycz** [comment]
Specify tensorflow version using `%tensorflow_version 1.x`

**Comment by oycz** [comment]
Specify tensorflow version using %tensorflow_version 1.x

**Comment by oycz** [comment]
Specify tensorflow version using `%tensorflow_version 1.x`

**Comment by rockerritesh** [comment]
@oycz Are u sure?
Send me screenshot.

**Comment by oycz** [comment]
![image](https://user-images.githubusercontent.com/44859230/92316203-548f8680-efb6-11ea-8e56-c915cb4f44eb.png)

**Comment by rockerritesh** [comment]
Oh Thanks!!
