### ISSUE TITLE
How to use the Virtual Batch Normalization class?

### ISSUE THREAD

**Issue by daanklijn** [tensorflow/gan#40]
I am currently trying the following using Kera's functional API:

```py
from tensorflow_gan.python.features import VBN

inputs = Input(shape=(2))
layer1 = Dense(10, activation="relu")(inputs)
layer2 = VBN(layer1)(layer1)
output = Dense(1)(layer2)
model = Model(inputs=inputs, outputs=output)
```

But this results in the following error:

```py
ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`.
```

Is this class compatible with the functional API or should I use it in a different way?

**Comment by aaronsarna** [comment]
This doesn't seem related to TF-GAN. Did you mean to post this in the main Tensorflow repo?

**Comment by daanklijn** [comment]
I am talking about the `from tensorflow_gan.python.features.VBN` class. AFAIK this class does not exist in the current Tensorflow module. Please correct me if I am wrong.

**Comment by aaronsarna** [comment]
Ah I see. Yeah, it's not currently implemented as a Keras layer, or even a tf1.layers.Layer. Doesn't look like it would be super hard to convert, though.
