### ISSUE TITLE
Inception score evaluation throwing error

### ISSUE THREAD

**Issue by shubham-malaviya** [tensorflow/gan#5]
tensorflow 2.0
images are of shape: (28,28,1)
**inception_score = tfgan.eval.inception_score(images)**

**error :** 
Shapes (2, 28, 28, 1) and [None, 299, 299, None] are incompatible

**Comment by shubham-malaviya** [comment]
> tensorflow 2.0
> images are of shape: (28,28,1)
> **inception_score = tfgan.eval.inception_score(images)**
> 
> **error :**
> Shapes (2, 28, 28, 1) and [None, 299, 299, None] are incompatible

When images are resized into height and width of (299,299) following error is thrown:
**ValueError: `run_image_classifier` doesn't work in eager.**

**Comment by skgg** [comment]
Me too.
It's frustrating that the evaluation does not support eager execution.
Is there any simple way to calculate the inception score and FID in TF2.0?

**Comment by joel-shor** [comment]
I believe it does work, but the shape needs to be 4D, not 3D. The following, for instance, runs:

```
import tensorflow.compat.v2 as tf
tf.enable_v2_behavior()
import tensorflow_gan as tfgan
tfgan.eval.inception_score(tf.zeros([1, 28, 28, 3]))
```

Please reopen it if you think this is in error.
